name: ihatework
version: '1.0.0'
summary: Cross-platform local media processing tool
description: |
  IHateWork is a powerful local media processing tool that runs completely offline.

  Features:
  - PDF: Merge, split, compress, rotate, watermark, encrypt/decrypt
  - Video: Compress, convert formats
  - Audio: Convert formats, extract from video
  - Media: Trim video and audio files
  - Image: Create GIFs, resize, crop, rotate, flip, enlarge

  All processing is done locally on your machine - no files are uploaded to any server.

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  ihatework:
    command: ihatework
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - browser-support
      - audio-playback

parts:
  ihatework:
    plugin: nil
    source: .
    build-packages:
      - nodejs
      - npm
      - python3
      - python3-pip
      - python3-venv
    stage-packages:
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libxss1
      - libxtst6
      - xdg-utils
      - libatspi2.0-0
      - libdrm2
      - libgbm1
      - libxcb-dri3-0
    override-build: |
      # Install Node.js dependencies
      npm ci

      # Build Python backend
      python3 -m pip install pyinstaller
      python3 -m pip install -r python/requirements.txt
      node scripts/build-python.js

      # Build Electron app
      npm run build
      npm run build:unpack

      # Copy to snap directory
      cp -r dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/
